apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app  # This should match the label in the Deployment
  ports:
    - protocol: TCP
      port: 80  # External port that you will use to access the app
      targetPort: 8080  # Internal port (your Spring Boot app)
  type: LoadBalancer  # Exposes the app via a public IP in Azure
